device: cuda
seed: 0

base_lr: 1e-4
num_iterations: 10000
max_events: 30
termination_factor: 3.

start_pos: [[1., 1.5], [1.5, 2.5]]
n_balls: ?? # Set by code

event_fn:
    _target_: try_ODE.EventFn
  #learn_pymunk.EventFn
    n_balls: ${n_balls}
    n_event_latent: 30
    init_factor: 5.


log_interval: 1
plot_interval: 10
save_interval: 10

experiment: test

hydra:
  # name: ${env}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/learn_pymunk/${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/learn_pymunk/${now:%H%M%S}
    subdir: ${hydra.job.num}
  # launcher:
  #   params:
  #     queue_parameters:
  #       slurm:
  #         max_num_timeout: 100000
  #         time: 4319
  #         partition: learnfair
  #         #partition: priority
  #   mem_limit: 64
