device: cuda
#cuda
seed: 0

base_lr: 1e-4
num_iterations: 10000
max_events: 30
termination_factor: 3.

#start_pos: [[1., 1.5], [1.5, 2.5]]
n_objects: 2 # Set by code
n_all_ob: 3
n_actions: 883   #TODO:
datasets_path: /home/kewen/phyre_ODE/datasets_vec/00000.000
#/mnt/d/phyre/datasets_vec/00000.000
event_fn:
    _target_: try_ODE.EventFn
  #learn_pymunk.EventFn
    n_objects: ${n_objects}
    n_event_latent: 30
    init_factor: 5.


log_interval: 1
plot_interval: 319
save_interval: 10

experiment: test

hydra:
  # name: ${env}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/learn_pymunk/${now:%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/learn_pymunk/${now:%H%M%S}
    subdir: ${hydra.job.num}
  # launcher:
  #   params:
  #     queue_parameters:
  #       slurm:
  #         max_num_timeout: 100000
  #         time: 4319
  #         partition: learnfair
  #         #partition: priority
  #   mem_limit: 64
